name: Build and Deploy .NET Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore **/*.csproj  # Busca cualquier .csproj en subcarpetas

      - name: Build application
        run: dotnet build **/*.csproj --configuration Release

      - name: Publish application
        run: dotnet publish **/*.csproj --configuration Release --output ./published

      - name: Deploy to server (ejemplo de despliegue)
        run: |
          echo "Despliegue simulado"
